#!/bin/sh
set -e

# Auto-fix formatting issues
echo "Running cargo fmt..."
cargo fmt

# Run tests
echo "Running tests..."
cargo test

# Run clippy
echo "Running clippy checks..."
cargo clippy -- -D warnings

# Run 'cargo check' to check for compilation errors
echo "Running cargo check..."
cargo check --all
