name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

# Add permissions required for creating releases and uploading assets
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build-and-upload:
    needs: create-release
    name: Build and upload for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rs-git-msg
            asset_name: rs-git-msg-linux-amd64
          - os: macos-latest
            artifact_name: rs-git-msg
            asset_name: rs-git-msg-macos-amd64

    steps:
    - uses: actions/checkout@v3
    
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build release binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Rename binary for upload
      run: |
        cp ./target/release/${{ matrix.artifact_name }} ./target/release/${{ matrix.asset_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/${{ matrix.asset_name }}
